//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazeRunner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazeRunner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeathScreen {
            get {
                object obj = ResourceManager.GetObject("DeathScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gremlin {
            get {
                object obj = ResourceManager.GetObject("gremlin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream gremlinHit {
            get {
                return ResourceManager.GetStream("gremlinHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;wall&gt;
        ///		&lt;x&gt;0&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		&lt;width&gt;1000&lt;/width&gt;
        ///		&lt;height&gt;25&lt;/height&gt;
        ///	&lt;/wall&gt;
        ///	&lt;wall&gt;
        ///		&lt;x&gt;0&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		&lt;width&gt;20&lt;/width&gt;
        ///		&lt;height&gt;200&lt;/height&gt;
        ///	&lt;/wall&gt;
        ///	&lt;wall&gt;
        ///		&lt;x&gt;0&lt;/x&gt;
        ///		&lt;y&gt;300&lt;/y&gt;
        ///		&lt;width&gt;20&lt;/width&gt;
        ///		&lt;height&gt;200&lt;/height&gt;
        ///	&lt;/wall&gt;
        ///	&lt;wall&gt;
        ///		&lt;x&gt;0&lt;/x&gt;
        ///		&lt;y&gt;480&lt;/y&gt;
        ///		&lt;width&gt;1000&lt;/width&gt;
        ///		&lt;height&gt;20&lt;/height&gt;
        ///	&lt;/wall&gt;
        ///	&lt;wall&gt;
        ///		&lt;x&gt;100&lt;/x&gt;
        ///		&lt;y&gt;100&lt;/y&gt;
        ///		&lt;width&gt;20&lt;/width&gt;
        ///		&lt;height&gt;200&lt;/height&gt;
        ///	&lt;/wall&gt;
        ///	&lt;wall&gt;
        ///		&lt;x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;wall&gt;
        ///		&lt;x&gt;0&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		&lt;width&gt;1000&lt;/width&gt;
        ///		&lt;height&gt;20&lt;/height&gt;
        ///	&lt;/wall&gt;
        ///	&lt;wall&gt;
        ///		&lt;x&gt;0&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		&lt;width&gt;20&lt;/width&gt;
        ///		&lt;height&gt;200&lt;/height&gt;
        ///	&lt;/wall&gt;
        ///	&lt;wall&gt;
        ///		&lt;x&gt;0&lt;/x&gt;
        ///		&lt;y&gt;300&lt;/y&gt;
        ///		&lt;width&gt;20&lt;/width&gt;
        ///		&lt;height&gt;200&lt;/height&gt;
        ///	&lt;/wall&gt;
        ///	&lt;wall&gt;
        ///		&lt;x&gt;0&lt;/x&gt;
        ///		&lt;y&gt;480&lt;/y&gt;
        ///		&lt;width&gt;1000&lt;/width&gt;
        ///		&lt;height&gt;20&lt;/height&gt;
        ///	&lt;/wall&gt;
        ///	&lt;wall&gt;
        ///		&lt;x&gt;100&lt;/x&gt;
        ///		&lt;y&gt;100&lt;/y&gt;
        ///		&lt;width&gt;150&lt;/width&gt;
        ///		&lt;height&gt;15&lt;/height&gt;
        ///	&lt;/wall&gt;
        ///	&lt;wall&gt;
        ///		&lt;x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuScreen {
            get {
                object obj = ResourceManager.GetObject("MenuScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player {
            get {
                object obj = ResourceManager.GetObject("player", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream playerHit {
            get {
                return ResourceManager.GetStream("playerHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WinScreen {
            get {
                object obj = ResourceManager.GetObject("WinScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
